name: Daily Dependency Update

on:
  schedule:
    - cron: '0 22 * * *' # Runs at 10:00 PM UTC every day
  workflow_dispatch: # lets you manually trigger it too

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Change if needed

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npm update

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b dependency-update-$(date +%F)
          git add package*.json package-lock.json
          git commit -m "chore: daily dependency update"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: daily dependency update"
          branch: dependency-update
          title: 'Daily Dependency Update'
          body: 'Automated dependency update at 10 PM (UTC)'
